### ISSUE TITLE
DOES NOT work on kubuntu 17.10

### ISSUE THREAD

**Issue by ghost** [Spiritdude/Nautilus_Thumbnailer_STL#1]
![image](https://user-images.githubusercontent.com/14994740/42735163-a018554e-884f-11e8-9662-1349b9c355f6.png)
I got some fresh errors for you !

**Comment by ghost** [comment]
The file explorer is "dolphin"

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/14994740/42735193-22af0156-8850-11e8-8510-1b522e39d2e0.png)

**Comment by Spiritdude** [comment]
I didn't test it with Dolphin, but Nautilus (try it instead of Dolphin) it should work - when you check `which openscad`, what's your output?

**Comment by ghost** [comment]
It does work with Nautilus ! 
![image](https://user-images.githubusercontent.com/14994740/42736435-3c878ec4-8867-11e8-8496-6411d83d4ecb.png)

**Comment by ghost** [comment]
But still nothing on Dolphin, do you know why ? 
![image](https://user-images.githubusercontent.com/14994740/42736447-6ce30224-8867-11e8-90a2-67d0204d2993.png)

**Comment by ghost** [comment]
The output is : 
leo@leo-ThinkPad-T410:~$ which openscad
/usr/bin/openscad

**Comment by Spiritdude** [comment]
If you get it working with Dolphin, let me know the changes it required. 

Remember this package is called "Nautilus Thumbnailer STL" if it happens to support other file browsers good, otherwise it focuses on Nautilus for now.
