### ISSUE TITLE
Doesn't work on Ubuntu 19.10?

### ISSUE THREAD

**Issue by KlausHans** [Spiritdude/Nautilus_Thumbnailer_STL#3]
I got no luck to get this running on my Ubuntu 19.10.
I installed stl2pov and PovRay and made that link to my home folder.
Then i issued make install on the code of this repo. Everything seemed fine, i got no errors. But nether after i reopened "Files" nor after a reboot i got stl thumbnails.

Any idea?

**Comment by KlausHans** [comment]
`rm -r ~/.cache/thumbnails` did the trick. Works now as expected.

**Comment by SeaGull711** [comment]
I had to clear the cache too.  I'm really glad to see that solution.  I'm really excited about getting this working!
